tags_list:
    [
        "низкое_качество_стирки_или_чистки",
        "не_заменили_ковры_вовремя",
        "клиент_хочет_добавить_ковры",
        "клиент_хочет_меньше_ковров",
        "погашение_долга",
        "расторжение_договора",
        "возобновление_услуг",
        "долго_нет_ответа_на_заявку",
        "лишняя_доставка",
        "доставили_не_те_ковры",
        "не_выставлен_вовремя_счет",
        "неверная_сумма_в_счете",
        "ковер_забрали_без_причины",
        "забрали_не_тот_ковер",
        "доставили_ковры_на_неверный_адрес",
        "менеджер_нагрубил_клиенту",
        "клиент_недоволен_ценами",
        "новый_клиент_заключение_договора",
        "консультация_или_уточнение_деталей",
        "поменять_спецификации",
        "клиент_уходит_к_конкурентам",
        "приостановить_услуги",
        "ошибка_в_документах"
    ]